inherit_from: .rubocop_todo.yml

Style/AsciiComments:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Metrics/AbcSize:
  Max: 100

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 42

Metrics/LineLength:
  Max: 180

Metrics/MethodLength:
  Max: 64

Metrics/PerceivedComplexity:
  Max: 42

Metrics/BlockLength:
  Enabled: false
